import type { Metadata } from "next";
import "./globals.css";
import { M_PLUS_Rounded_1c } from "next/font/google";
import Providers from "@/components/Providers";

const mplus = M_PLUS_Rounded_1c({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-mplus"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={mplus.variable}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
